.\"     $OpenBSD$
.\"
.\" Copyright (c) 2017 Wesley Mouedine Assaby <milo974@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt RMSPAMS.CONF 5
.Os
.Sh NAME
.Nm rmspams.conf
.Nd rmspams configuration file
.Sh DESCRIPTION
.Nm
is a text file containing one variable assignment of the form
.Ar variable Ns = Ns Ar value
per line.
Blank lines and lines starting with a hash mark
.Pq Sq #
are ignored.
.Pp
The following variables are supported:
.Bl -tag -width WHITE_LIST
.It Ic MAILDIR_PATH
The directory where the maildir folders are located.
The default is
.Pa /var/mailserver/mail .
.Pp
The names of the first level of subdirectories are expected to be
MX domain names.
The names of the second level of subdirectories are expected to be
email address local parts, for example user names.
Each second level subdirectory is expected to contain a
.Pa .Spam
subdirectory containing a
.Pa cur
maildir folder.
.It Ic WHITE_LIST
A file containing fully qualified domain names of SMTP servers
trusted to not send spam, one per line.
The default is
.Pa /etc/mail/whitesmtp .
.El
.Sh FILES
.Bl -tag -width /etc/mail/rmspams.conf -compact
.It Pa /etc/mail/rmspams.conf
.El
.Sh SEE ALSO
.Xr rmspams 8
.Sh AUTHORS
The
.Nm
file format was designed by
.An Wesley Mouedine Assaby Aq Mt milo974@gmail.com .
