.\"    $OpenBSD: rmspams.8 2017/04/14 Exp $
.\"
.\" Copyright (c) 2016 Wesley Mouedine Assaby <milo974@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 14 2017 $
.Dt RMSPAMS 8
.Os
.Sh NAME
.Nm rmspams
.Nd remove spams from a junk folder
.Sh SYNOPSIS
.Nm rmspams
.Op Fl dnv
.Ar email
.Sh DESCRIPTION
For each message in the junk folder of the user with the given
.Ar email
address,
.Nm
adds the names of mail servers whose IP addresses are found
in Received: headers to the
.Pa blacksmtp
table, except those that are listed in
.Pa whitesmtp ,
and deletes each successfully processed message from the junk folder.
.Pp
Only maildir style mailboxes are supported.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Debug mode: use the
.Xr ksh 1
.Fl x
option.
.It Fl n
Dry run: don't remove messages and don't populate the
.Pa blacksmtp
table.
.It Fl v
Produce verbose output, using the following shorthands:
.Bl -tag -width 3n -compact
.It Pq a
Adding the server to
.Pa blacksmtp .
.It Pq b
The server is already listed in
.Pa blacksmtp .
.It Pq r
Nothing to do with this IP address.
.It Pq w
The server was found in
.Pa whitesmtp .
.El
.El
.Sh FILES
.Bl -tag -width /var/db/rmspams/blacksmtp -compact
.It Pa /etc/mail/rmspams.conf
Configuration file for
.Nm
.It Pa /etc/mail/whitesmtp
Allowed senders (FQDN)
.It Pa /var/db/rmspams/blacksmtp
Blocked IP addresses, filled by
.Nm
.El
.Sh SEE ALSO
.Xr rmspams.conf 5
.Sh AUTHORS
.Nm
was written by
.An Wesley Mouedine Assaby Aq Mt milo974@gmail.com .